name: Validate Terraform

on:
  push:
    branches:
      - master
      - main
      - develop

  pull_request:
    branches:
      - master
      - main
      - develop

  workflow_dispatch:

#  schedule:
#    - cron: '0 0 * * 0'

jobs:
  build-webapp:
    name: Validate Terraform
    runs-on: ${{ matrix.environment }}
    strategy:
      matrix:
        environment:
          - ubuntu-latest

    env:
      ACTIONS_RUNNER_DEBUG: false
      TF_LOG: INFO
      ARM_CLIENT_ID: ""
      ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ""
      ARM_TENANT_ID: ""

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Version
        run: terraform -v
        
      - name: Verify encoding
        shell: pwsh
        run: ./scripts/verify-encoding.ps1

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check