trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  - name: TF_LOG
    value: INFO
  - name: System.Debug
    value: 'false'

stages:
  - stage: Terraform_CI
    displayName: Terraform Validate
    jobs:
      - job: Terraform_CI
        displayName: Terraform Validate
        pool:
          vmImage: windows-latest
        steps:
          - checkout: self
            fetchDepth: 0
            
          - task: PowerShell@2
            displayName: 'Fix Encoding'
            inputs:
              targetType: 'filePath'
              filePath: $(System.DefaultWorkingDirectory)/scripts/verify-encoding.ps1
              arguments: '-Autofix'
              pwsh: true
              workingDirectory: $(System.DefaultWorkingDirectory)

          - task: TerraformInstaller@1
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: 'latest'

          - script: terraform -v
            displayName: 'Terraform Version'

          - script: terraform init -backend=false
            displayName: 'Terraform Init'

          - script: terraform validate
            displayName: 'Terraform Validate'

          - script: terraform fmt -check
            displayName: 'Terraform Format'
