trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

variables:
  - name: TF_LOG
    value: INFO

stages:
  - stage: "Terraform_CI"
    displayName: "Terraform Validate"
    jobs:
      - job: Terraform_CI
        displayName: "Terraform Validate"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: TerraformInstaller@0
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: 'latest'

          - script: terraform -v
            displayName: 'Terraform Version'

          - script: terraform init -backend=false
            displayName: 'Terraform Init'

          - script: terraform validate
            displayName: 'Terraform Validate'

          - script: terraform fmt -check
            displayName: 'Terraform Format'
